name = "LatBench"
uuid = "2bd488d2-d3e6-46ee-afb3-5515643db0c7"
version = "0.1.0"
authors = ["sota shimozono <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
julia = "1.10"
QuadGK = "2.11.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
